apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
  annotations:
    kubernetes.io/ingress.class: nginx
    # Basic Authentication Settings
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: longhorn-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - Longhorn UI"
    # Timeouts and Upload limits for Large Backups/Support Bundles
    nginx.ingress.kubernetes.io/proxy-body-size: "10000m"
    nginx.ingress.kubernetes.io/read-timeout: "600"
    nginx.ingress.kubernetes.io/send-timeout: "600"
spec:
  tls:
  - hosts:
    - longhorn.pdx-nwa-k8s-ingress.nvidia.com
    secretName: longhorn-tls-secret
  rules:
  - host: longhorn.pdx-nwa-k8s-ingress.nvidia.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
