#!/usr/bin/env bash
# bake-maintenance-images.sh - Version 1.6
# Features: Timestamped rotation of blacklist files and granular package logging.

set -u

# --- CONFIGURATION ---
IMAGES_ROOT="/cm/images"
BLACKLIST_FILE="99-ndt-blacklist.conf"
MODPROBE_DIR="etc/modprobe.d"

# --- KERNEL MODULES TO BLACKLIST ---
BLACKLIST_MODULES=("qedr" "qede" "irdma" "nouveau")

# --- PACKAGES TO REMOVE ---
PACKAGES_TO_REMOVE=("ibacm")

# --- PACKAGES TO INSTALL ---
PACKAGES_TO_INSTALL=("tcpdump" "pciutils" "ethtool")

# Colors
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m'

# --- GENERATE BLACKLIST CONTENT ---
GEN_HEADER="# Generated by NDT - $(date +%F)"
FILE_CONTENT="${GEN_HEADER}\n"
for mod in "${BLACKLIST_MODULES[@]}"; do
    FILE_CONTENT="${FILE_CONTENT}blacklist ${mod}\n"
done

echo -e "${BLUE}[INFO] Starting Image Maintenance...${NC}"

shopt -s nullglob
worker_images=("$IMAGES_ROOT"/*worker*)

for img_path in "${worker_images[@]}"; do
    if [[ -d "$img_path" && -d "${img_path}/etc" ]]; then
        IMG_NAME=$(basename "$img_path")
        echo -e "${BLUE}>>> Image: $IMG_NAME${NC}"

        # --- 1. BLACKLIST ROTATION & WRITE ---
        DEST_DIR="${img_path}/${MODPROBE_DIR}"
        FULL_DEST_PATH="${DEST_DIR}/${BLACKLIST_FILE}"
        
        sudo mkdir -p "$DEST_DIR"
        
        # Check if the file already exists and RENAME it
        if [[ -f "$FULL_DEST_PATH" ]]; then
            # Generate a specific timestamp for this rotation
            OLD_TS=$(date +%F-%H%M%S)
            NEW_BACKUP_NAME="${FULL_DEST_PATH}.${OLD_TS}.old"
            
            echo -e "    ${YELLOW}[ROTATE]${NC} Existing blacklist found. Archiving to: $(basename "$NEW_BACKUP_NAME")"
            sudo mv "$FULL_DEST_PATH" "$NEW_BACKUP_NAME"
        fi

        # Write the new configuration
        echo -e "$FILE_CONTENT" | sudo tee "$FULL_DEST_PATH" > /dev/null
        echo -e "    ${GREEN}[OK]${NC} New blacklist applied: ${BLACKLIST_MODULES[*]}"

        # --- 2. PACKAGE REMOVAL ---
        for pkg in "${PACKAGES_TO_REMOVE[@]}"; do
            echo -ne "    ${YELLOW}[REMOVE]${NC} $pkg... "
            if sudo yum --installroot="$img_path" -y remove "$pkg" &>/dev/null; then
                echo -e "${GREEN}Done.${NC}"
            else
                echo -e "${RED}Not present/Failed.${NC}"
            fi
        done

        # --- 3. PACKAGE INSTALLATION ---
        for pkg in "${PACKAGES_TO_INSTALL[@]}"; do
            echo -ne "    ${CYAN}[INSTALL]${NC} $pkg... "
            if sudo yum --installroot="$img_path" -y install "$pkg" &>/dev/null; then
                echo -e "${GREEN}Done.${NC}"
            else
                echo -e "${RED}Failed.${NC}"
            fi
        done
    fi
done

echo -e "\n${GREEN}[SUCCESS] All maintenance tasks complete.${NC}"
