#!/usr/bin/env bash
# bake-maintenance-images.sh - Version 1.4
# Handles Blacklisting (qedr/qede/irdma), Package Removal (ibacm), and Provisioning.

set -u

# --- CONFIGURATION ---
IMAGES_ROOT="/cm/images"
BLACKLIST_FILE="99-ndt-blacklist.conf"
MODPROBE_DIR="etc/modprobe.d"

# --- KERNEL MODULES TO BLACKLIST ---
# These are the specific QLogic/Marvell and Intel RDMA drivers to block
BLACKLIST_MODULES=(
    "qedr"
    "qede"
    "irdma"
    "nouveau"
)

# --- PACKAGES TO REMOVE ---
PACKAGES_TO_REMOVE=(
    "ibacm"
)

# --- PACKAGES TO INSTALL ---
PACKAGES_TO_INSTALL=(
    "tcpdump"
    "pciutils"
    "ethtool"
)

# Colors
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# --- GENERATE BLACKLIST CONTENT ---
GEN_HEADER="# Generated by NDT - $(date +%F) - Preventing Driver Conflicts"
FILE_CONTENT="${GEN_HEADER}\n"
for mod in "${BLACKLIST_MODULES[@]}"; do
    FILE_CONTENT="${FILE_CONTENT}blacklist ${mod}\n"
done

echo -e "${BLUE}[INFO] Initializing Image Maintenance Cycle...${NC}"
echo -e "${BLUE}[INFO] Blacklisting modules:${NC} ${BLACKLIST_MODULES[*]}"

shopt -s nullglob
worker_images=("$IMAGES_ROOT"/*worker*)

for img_path in "${worker_images[@]}"; do
    if [[ -d "$img_path" && -d "${img_path}/etc" ]]; then
        IMG_NAME=$(basename "$img_path")
        echo -e "${BLUE}>>> Processing Image: $IMG_NAME${NC}"

        # --- 1. KERNEL BLACKLIST ---
        DEST_DIR="${img_path}/${MODPROBE_DIR}"
        FULL_DEST_PATH="${DEST_DIR}/${BLACKLIST_FILE}"
        sudo mkdir -p "$DEST_DIR"
        
        if [[ -f "$FULL_DEST_PATH" ]]; then
            sudo mv "$FULL_DEST_PATH" "${FULL_DEST_PATH}.$(date +%s).old"
        fi
        echo -e "$FILE_CONTENT" | sudo tee "$FULL_DEST_PATH" > /dev/null
        echo -e "    ${GREEN}[OK]${NC} Blacklist applied."

        # --- 2. PACKAGE PURGE (e.g., ibacm) ---
        if [ ${#PACKAGES_TO_REMOVE[@]} -gt 0 ]; then
            echo -ne "    ${YELLOW}[INFO]${NC} Purging requested packages... "
            # Using yum/dnf --installroot to modify the image chroot directly
            sudo yum --installroot="$img_path" -y remove "${PACKAGES_TO_REMOVE[@]}" &>/dev/null
            echo -e "${GREEN}Done.${NC}"
        fi

        # --- 3. ESSENTIAL TOOL PROVISIONING ---
        if [ ${#PACKAGES_TO_INSTALL[@]} -gt 0 ]; then
            echo -ne "    ${YELLOW}[INFO]${NC} Installing diagnostic tools... "
            sudo yum --installroot="$img_path" -y install "${PACKAGES_TO_INSTALL[@]}" &>/dev/null
            echo -e "${GREEN}Done.${NC}"
        fi
    fi
done

echo -e "\n${GREEN}[SUCCESS] Blacklist and Package Maintenance complete for all worker images.${NC}"
