#!/usr/bin/env bash
# bake-maintenance-images.sh - Version 1.7
# Logic: Skips package sections if arrays are empty to avoid "Failed" output.

set -u

# --- CONFIGURATION ---
IMAGES_ROOT="/cm/images"
BLACKLIST_FILE="99-ndt-blacklist.conf"
MODPROBE_DIR="etc/modprobe.d"

# --- KERNEL MODULES TO BLACKLIST ---
BLACKLIST_MODULES=("qedr" "qede" "irdma" "nouveau")

# --- PACKAGES TO REMOVE ---
# Leave empty () or ("") to skip
PACKAGES_TO_REMOVE=("ibacm")

# --- PACKAGES TO INSTALL ---
# Leave empty () or ("") to skip
PACKAGES_TO_INSTALL=("")

# Colors
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m'

# --- GENERATE BLACKLIST CONTENT ---
GEN_HEADER="# Generated by NDT - $(date +%F)"
FILE_CONTENT="${GEN_HEADER}\n"
for mod in "${BLACKLIST_MODULES[@]}"; do
    FILE_CONTENT="${FILE_CONTENT}blacklist ${mod}\n"
done

echo -e "${BLUE}[INFO] Starting Image Maintenance...${NC}"

shopt -s nullglob
worker_images=("$IMAGES_ROOT"/*worker*)

for img_path in "${worker_images[@]}"; do
    if [[ -d "$img_path" && -d "${img_path}/etc" ]]; then
        IMG_NAME=$(basename "$img_path")
        echo -e "${BLUE}>>> Image: $IMG_NAME${NC}"

        # --- 1. BLACKLIST ---
        DEST_DIR="${img_path}/${MODPROBE_DIR}"
        FULL_DEST_PATH="${DEST_DIR}/${BLACKLIST_FILE}"
        sudo mkdir -p "$DEST_DIR"
        
        if [[ -f "$FULL_DEST_PATH" ]]; then
            OLD_TS=$(date +%F-%H%M%S)
            sudo mv "$FULL_DEST_PATH" "${FULL_DEST_PATH}.${OLD_TS}.old"
            echo -e "    ${YELLOW}[ROTATE]${NC} Archived existing blacklist."
        fi
        echo -e "$FILE_CONTENT" | sudo tee "$FULL_DEST_PATH" > /dev/null
        echo -e "    ${GREEN}[OK]${NC} Blacklist applied."

        # --- 2. PACKAGE REMOVAL (Only if array is not empty) ---
        if [[ ${#PACKAGES_TO_REMOVE[@]} -gt 0 && -n "${PACKAGES_TO_REMOVE[0]}" ]]; then
            for pkg in "${PACKAGES_TO_REMOVE[@]}"; do
                if [[ -n "$pkg" ]]; then
                    echo -ne "    ${YELLOW}[REMOVE]${NC} $pkg... "
                    if sudo yum --installroot="$img_path" -y remove "$pkg" &>/dev/null; then
                        echo -e "${GREEN}Done.${NC}"
                    else
                        echo -e "${RED}Not present/Skipped.${NC}"
                    fi
                fi
            done
        fi

        # --- 3. PACKAGE INSTALLATION (Only if array is not empty) ---
        if [[ ${#PACKAGES_TO_INSTALL[@]} -gt 0 && -n "${PACKAGES_TO_INSTALL[0]}" ]]; then
            for pkg in "${PACKAGES_TO_INSTALL[@]}"; do
                if [[ -n "$pkg" ]]; then
                    echo -ne "    ${CYAN}[INSTALL]${NC} $pkg... "
                    if sudo yum --installroot="$img_path" -y install "$pkg" &>/dev/null; then
                        echo -e "${GREEN}Done.${NC}"
                    else
                        echo -e "${RED}Failed.${NC}"
                    fi
                fi
            done
        fi
    fi
done

echo -e "\n${GREEN}[SUCCESS] Image maintenance complete.${NC}"
