apiVersion: nv-ipam.nvidia.com/v1alpha1
kind: IPPool
metadata:
  name: sriovnet-pool-rail-0
  namespace: network-operator
spec:
  subnet: 192.168.0.0/24
  perNodeBlockSize: 32
  gateway: 192.168.0.1
  exclusions:
    # Reserved exactly the first 3 IPs
    - startIP: 192.168.0.1
      endIP: 192.168.0.3
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: node-role.kubernetes.io/worker
        operator: Exists
---
apiVersion: nv-ipam.nvidia.com/v1alpha1
kind: IPPool
metadata:
  name: sriovnet-pool-rail-1
  namespace: network-operator
spec:
  subnet: 192.168.1.0/24
  perNodeBlockSize: 32
  gateway: 192.168.1.1
  exclusions:
    # Reserved exactly the first 3 IPs
    - startIP: 192.168.1.1
      endIP: 192.168.1.3
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: node-role.kubernetes.io/worker
        operator: Exists
